name: Build SR-AI APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Android APK
        uses: Chethan-S/pwa-to-apk-action@v1.0.1
        with:
          # Isse tumhari live website ka APK banega
          pwa_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          app_name: "SR AI Mastermind"
          app_id: "com.srai.mastermind"
          
