name: Build SR-AI APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Android APK
        # Hum ek stable aur live robot use kar rahe hain
        uses: floscha/pwa-to-apk-action@v1
        with:
          url: "https://simmokhan0099-commits.github.io/SR-AI-MASTERMIND/"
          name: "SR AI Mastermind"
          
